-- AlterTable
ALTER TABLE "Board" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Status" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
